name: Keep Render Service Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # mỗi 10 phút (UTC)
  workflow_dispatch:        # cho phép chạy tay

jobs:
  ping-service:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health check endpoint
        run: |
          curl -s https://myenglish-wn3l.onrender.com/health/check > /dev/null